In [44]:
import random
import numpy as np
import pandas as pd

data_o = pd.read_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/Orders_final.csv')
data_t = pd.read_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/Online_Retail_new_one.csv')
#print(len(data_t))
merged_df = pd.merge(data_o, data_t, on='InvoiceNo', how='left')
#result_df = merged_df[merged_df['CustomerID_y'].notnull()][['Invoice_u', 'InvoiceNo','StockCode','Description','Quantity','InvoiceDate_y','UnitPrice','CustomerID_y','Country']]
#result_df.rename(columns={'InvoiceDate_y': 'InvoiceDate','CustomerID_y':'CustomerID'}, inplace=True)
#result_df.head(10)
#print(len(result_df))
#result_df.to_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/Online_Retail_new_one.csv',index=False)

#merged_df = pd.merge(data_c[[CustomerID]], data_t, on='CustomerID', how='left')
#merged_df = merged_df = pd.merge(df1, df2, on='ID', how='left')
#len(merged_df)
#CustomerID
#len(data_o)
#df_unique = data_o.drop_duplicates(subset=['StockCode'], keep=False)
#df_unique.to_csv('/Users/bhoomikan/Desktop/Datawarehousing/Productsf_new.csv',index=False)
#xls = pd.ExcelFile('/Users/bhoomikan/Desktop/Datawarehousing/Productsf_new.csv')
#sheet_names = xls.sheet_names
#print(sheet_names)
#df_unique = data_o.drop_duplicates(subset=['StockCode'], keep=False)
#duplicate_counts = df_unique['StockCode'][df_unique.duplicated(subset='StockCode', keep=False)].value_counts()
#print(duplicate_counts)
#df_unique = data_o.drop_duplicates(subset=['StockCode'])
#df_unique.to_excel('/Users/bhoomikan/Desktop/Datawarehousing/Productsf_new.xlsx',index=False)
#49353
#10000
#1036508

In [100]:
#1. Transactions
final_data = pd.read_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/Online_Retail.csv')
print(final_data.info())
print(final_data.isnull().sum())
print(final_data[final_data['Description'].isnull()].head(30))
final_data = final_data.dropna(subset = ['Description'])
print(final_data.info())
print(final_data.isnull().sum())
unique_customer_id = final_data['CustomerID'].unique()
# Impute the missing values in the CustomerID
def replace_with_random(value, array):
    if pd.isnull(value) or value==0:
        return np.random.choice(array)
    else:
        return value

# Apply the function to the desired column
#final_data['CustomerID'].replace([np.inf, -np.inf,np.nan],0, inplace=True)
final_data['CustomerID'] = final_data['CustomerID'].apply(replace_with_random, args=(unique_customer_id,))
final_data.dropna(subset=['CustomerID'], inplace=True)
print(final_data.info())

# Check the uniqueness of rows
print(len(final_data.drop_duplicates()))

# remove unique rows
final_data = final_data.drop_duplicates()

# Recheck the uniqueness of rows
print(len(final_data))

print(final_data.info())

print(final_data[final_data['CustomerID'].isnull()].head(60))
# Convert it to CSV
final_data.to_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/Online_Retail_Sales.csv', index = False)
final_data = pd.read_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/Online_Retail_Sales.csv')
final_data['InvoiceNo'] = final_data['InvoiceNo'].astype('string')
final_data['StockCode'] = final_data['StockCode'].astype('string')
final_data['CustomerID'] = final_data['CustomerID'].astype(float)
final_data['CustomerID'] = final_data['CustomerID'].astype(int)
print(Customers.dtypes)
final_data['CustomerID'] = final_data['CustomerID'].astype('string')
#final_data['CustomerID']  = final_data['CustomerID'].astype('string')
final_data['Invoice_u']  = final_data['InvoiceNo'] +'_'+ final_data['StockCode']
new_column_order = ['Invoice_u', 'InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']
final_data = final_data[new_column_order]
final_data.to_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/transactions_29.csv', index = False)
print(final_data.head(10))
print(len(final_data))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531222 entries, 0 to 531221
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice_u    531222 non-null  object
 1   InvoiceNo    531222 non-null  object
 2   StockCode    531222 non-null  object
 3   Description  529769 non-null  object
 4   Quantity     531222 non-null  int64
 5   InvoiceDate  531222 non-null  object
 6   UnitPrice    531222 non-null  float64
 7   CustomerID   396681 non-null  float64
 8   Country      531222 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 36.5+ MB
None
Invoice_u           0
InvoiceNo           0
StockCode           0
Description      1453
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     134541
Country             0
dtype: int64
          Invoice_u InvoiceNo StockCode Description  Quantity    InvoiceDate  \
1886   536545_21134    536545     21134         NaN         1  12/1/10 14:32
1887   536546_22145    536546     22145         NaN         1  12/1/10 14:33
1888   536547_37509    536547     37509         NaN         1  12/1/10 14:33
1903  536549_85226A    536549    85226A         NaN         1  12/1/10 14:34
1904   536550_85044    536550     85044         NaN         1  12/1/10 14:34
1934   536552_20950    536552     20950         NaN         1  12/1/10 14:34
1935   536553_37461    536553     37461         NaN         3  12/1/10 14:35
1936   536554_84670    536554     84670         NaN        23  12/1/10 14:35
2308   536589_21777    536589     21777         NaN       -10  12/1/10 16:50
4223  536764_84952C    536764    84952C         NaN       -38  12/2/10 14:42
4224  536765_84952C    536765    84952C         NaN        19  12/2/10 14:43
6997   536995_35951    536995     35951         NaN        57  12/3/10 15:29
6998   536996_22712    536996     22712         NaN       -20  12/3/10 15:30
6999   536997_22028    536997     22028         NaN       -20  12/3/10 15:30
7000   536998_85067    536998     85067         NaN        -6  12/3/10 15:30
7001   536999_21421    536999     21421         NaN       110  12/3/10 15:32
7002   537000_21414    537000     21414         NaN       -22  12/3/10 15:32
7003   537001_21653    537001     21653         NaN        -6  12/3/10 15:33
7004   537002_21651    537002     21651         NaN        70  12/3/10 15:33
7005   537003_85126    537003     85126         NaN        -2  12/3/10 15:33
7006   537004_21814    537004     21814         NaN       -30  12/3/10 15:34
7007   537005_21692    537005     21692         NaN       -70  12/3/10 15:35
7008   537006_21648    537006     21648         NaN      -130  12/3/10 15:36
7009   537007_21172    537007     21172         NaN       -80  12/3/10 15:36
7010   537008_21161    537008     21161         NaN      -120  12/3/10 15:37
7011  537009_84534B    537009    84534B         NaN       -80  12/3/10 15:38
7012   537010_22162    537010     22162         NaN       -40  12/3/10 15:38
7013   537011_22139    537011     22139         NaN        -5  12/3/10 15:38
7014   537012_21535    537012     21535         NaN       -12  12/3/10 15:39
7015   537013_35965    537013     35965         NaN       -25  12/3/10 15:40

      UnitPrice  CustomerID         Country
1886        0.0         NaN  United Kingdom
1887        0.0         NaN  United Kingdom
1888        0.0         NaN  United Kingdom
1903        0.0         NaN  United Kingdom
1904        0.0         NaN  United Kingdom
1934        0.0         NaN  United Kingdom
1935        0.0         NaN  United Kingdom
1936        0.0         NaN  United Kingdom
2308        0.0         NaN  United Kingdom
4223        0.0         NaN  United Kingdom
4224        0.0         NaN  United Kingdom
6997        0.0         NaN  United Kingdom
6998        0.0         NaN  United Kingdom
6999        0.0         NaN  United Kingdom
7000        0.0         NaN  United Kingdom
7001        0.0         NaN  United Kingdom
7002        0.0         NaN  United Kingdom
7003        0.0         NaN  United Kingdom
7004        0.0         NaN  United Kingdom
7005        0.0         NaN  United Kingdom
7006        0.0         NaN  United Kingdom
7007        0.0         NaN  United Kingdom
7008        0.0         NaN  United Kingdom
7009        0.0         NaN  United Kingdom
7010        0.0         NaN  United Kingdom
7011        0.0         NaN  United Kingdom
7012        0.0         NaN  United Kingdom
7013        0.0         NaN  United Kingdom
7014        0.0         NaN  United Kingdom
7015        0.0         NaN  United Kingdom
<class 'pandas.core.frame.DataFrame'>
Int64Index: 529769 entries, 0 to 531221
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice_u    529769 non-null  object
 1   InvoiceNo    529769 non-null  object
 2   StockCode    529769 non-null  object
 3   Description  529769 non-null  object
 4   Quantity     529769 non-null  int64
 5   InvoiceDate  529769 non-null  object
 6   UnitPrice    529769 non-null  float64
 7   CustomerID   396681 non-null  float64
 8   Country      529769 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 40.4+ MB
None
Invoice_u           0
InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133088
Country             0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 529748 entries, 0 to 531221
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice_u    529748 non-null  object
 1   InvoiceNo    529748 non-null  object
 2   StockCode    529748 non-null  object
 3   Description  529748 non-null  object
 4   Quantity     529748 non-null  int64
 5   InvoiceDate  529748 non-null  object
 6   UnitPrice    529748 non-null  float64
 7   CustomerID   529748 non-null  float64
 8   Country      529748 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 40.4+ MB
None
529748
529748
<class 'pandas.core.frame.DataFrame'>
Int64Index: 529748 entries, 0 to 531221
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice_u    529748 non-null  object
 1   InvoiceNo    529748 non-null  object
 2   StockCode    529748 non-null  object
 3   Description  529748 non-null  object
 4   Quantity     529748 non-null  int64
 5   InvoiceDate  529748 non-null  object
 6   UnitPrice    529748 non-null  float64
 7   CustomerID   529748 non-null  float64
 8   Country      529748 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 40.4+ MB
None
Empty DataFrame
Columns: [Invoice_u, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []
CustomerID       string
FirstName        object
LastName         object
Gender           object
PhoneNumber      object
Date_of_Birth    object
CustomerSince    object
Country          object
dtype: object
       Invoice_u InvoiceNo StockCode                          Description  \
0  536365_85123A    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1   536365_71053    536365     71053                  WHITE METAL LANTERN
2  536365_84406B    536365    84406B       CREAM CUPID HEARTS COAT HANGER
3  536365_84029G    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4  536365_84029E    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
5   536365_22752    536365     22752         SET 7 BABUSHKA NESTING BOXES
6   536365_21730    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER
7   536366_22633    536366     22633               HAND WARMER UNION JACK
8   536366_22632    536366     22632            HAND WARMER RED POLKA DOT
9   536367_84879    536367     84879        ASSORTED COLOUR BIRD ORNAMENT

   Quantity   InvoiceDate  UnitPrice CustomerID         Country
0         6  12/1/10 8:26       2.55      17850  United Kingdom
1         6  12/1/10 8:26       3.39      17850  United Kingdom
2         8  12/1/10 8:26       2.75      17850  United Kingdom
3         6  12/1/10 8:26       3.39      17850  United Kingdom
4         6  12/1/10 8:26       3.39      17850  United Kingdom
5         2  12/1/10 8:26       7.65      17850  United Kingdom
6         6  12/1/10 8:26       4.25      17850  United Kingdom
7         6  12/1/10 8:28       1.85      17850  United Kingdom
8         6  12/1/10 8:28       1.85      17850  United Kingdom
9        32  12/1/10 8:34       1.69      13047  United Kingdom
529748

In [58]:
# 2) Products Table

import pandas as pd
import random

final_data = pd.read_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/transactions_29.csv')
products = final_data[['StockCode', 'Description', 'UnitPrice']]
print(len(products))

# Dropping duplicates based on 'StockCode' and keeping the first occurrence
products['StockCode'] = products['StockCode'].astype('string')
products['StockCode'] = products['StockCode'].str.upper()
products_unique = products.drop_duplicates(subset='StockCode')
print(len(products_unique))
products_unique['QuantityAvailable'] = np.random.randint(50, 251, size=len(products_unique))

print(products_unique.isnull().sum())
print(products_unique.head(15))
data_products = products_unique
unique_values = products_unique['StockCode'].unique()
print(len(unique_values))

for i in unique_values:
    filter_condition = final_data['StockCode'] == i
    date_min = pd.to_datetime(final_data.loc[filter_condition, 'InvoiceDate'].min())
    datetime_obj_minus_one_day = date_min - pd.Timedelta(days=1)
    datemin_val = datetime_obj_minus_one_day.date()
    data_products.loc[data_products['StockCode'] == i, 'Product_Created'] = datemin_val

    date_max = pd.to_datetime(final_data.loc[filter_condition, 'InvoiceDate'].max())
    datemax_val = date_max.date()
    data_products.loc[data_products['StockCode'] == i, 'Product_lastUpdated'] = datemax_val

ratings = [1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.50, 2.75, 3.0, 3.25, 3.5, 3.75, 4, 4.25, 4.50, 4.75, 5.0]
products_unique['Ratings'] = [random.choice(ratings) for i in range(len(data_products))]
data_products.to_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/products_final29.csv', index = False)

529769
3848
StockCode            0
Description          0
UnitPrice            0
QuantityAvailable    0
dtype: int64
   StockCode                          Description  UnitPrice  \
0     85123A   WHITE HANGING HEART T-LIGHT HOLDER       2.55
1      71053                  WHITE METAL LANTERN       3.39
2     84406B       CREAM CUPID HEARTS COAT HANGER       2.75
3     84029G  KNITTED UNION FLAG HOT WATER BOTTLE       3.39
4     84029E       RED WOOLLY HOTTIE WHITE HEART.       3.39
5      22752         SET 7 BABUSHKA NESTING BOXES       7.65
6      21730    GLASS STAR FROSTED T-LIGHT HOLDER       4.25
7      22633               HAND WARMER UNION JACK       1.85
8      22632            HAND WARMER RED POLKA DOT       1.85
9      84879        ASSORTED COLOUR BIRD ORNAMENT       1.69
10     22745           POPPY'S PLAYHOUSE BEDROOM        2.10
11     22748            POPPY'S PLAYHOUSE KITCHEN       2.10
12     22749    FELTCRAFT PRINCESS CHARLOTTE DOLL       3.75
13     22310              IVORY KNITTED MUG COSY        1.65
14     84969   BOX OF 6 ASSORTED COLOUR TEASPOONS       4.25

    QuantityAvailable
0                  85
1                  66
2                  98
3                  85
4                 239
5                 199
6                  99
7                 134
8                 250
9                 147
10                246
11                184
12                121
13                 99
14                165
3848

/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/354533854.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products['StockCode'] = products['StockCode'].astype('string')
/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/354533854.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products['StockCode'] = products['StockCode'].str.upper()
/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/354533854.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products_unique['QuantityAvailable'] = np.random.randint(50, 251, size=len(products_unique))
/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/354533854.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_products.loc[data_products['StockCode'] == i, 'Product_Created'] = datemin_val
/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/354533854.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_products.loc[data_products['StockCode'] == i, 'Product_lastUpdated'] = datemax_val
/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/354533854.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products_unique['Ratings'] = [random.choice(ratings) for i in range(len(data_products))]

In [66]:
#3) Orders Table

Orders = final_data[['InvoiceNo', 'InvoiceDate', 'CustomerID', 'Quantity', 'UnitPrice']]
print(len(Orders))
Orders['TotalAmount'] = Orders['Quantity'] * Orders['UnitPrice']

# Group by 'InvoiceNo' and sum the 'TotalAmount' for each group
invoice_totals = Orders.groupby('InvoiceNo')['TotalAmount'].sum().reset_index()


# Drop duplicate 'InvoiceNo' from Orders to get unique rows
Orders['InvoiceNo'] = Orders['InvoiceNo'].str.upper()
Orders_unique = Orders.drop_duplicates(subset='InvoiceNo')
print(len(Orders_unique))
# Merge the summed totals back with the unique InvoiceNo rows
Orders_final = pd.merge(Orders_unique[['InvoiceNo', 'InvoiceDate', 'CustomerID']], 
                        invoice_totals, on='InvoiceNo')

# Round the 'TotalAmount' column to two decimal places
Orders_final['TotalAmount'] = Orders_final['TotalAmount'].round(2)
payment_modes = ['Credit Card', 'Debit Card', 'PayPal', 'Bank Transfer', 'Cash', 'Check', 'Mobile Payments', 'Gift Card']
probabilities = [0.3, 0.3, 0.1, 0.1, 0.05, 0.03, 0.1, 0.02]  # Adjusted to sum to 1

# Generate the PaymentMode column
np.random.seed(0)  # For reproducibility
payment_mode_column = np.random.choice(payment_modes, size=len(Orders_final), p=probabilities)

# Add the PaymentMode column to the DataFrame
Orders_final['PaymentMode'] = payment_mode_column
print(Orders_final.isnull().sum())
print(Orders_final.info())
print(Orders_final.head(20))
print(len(Orders_final))
Orders_final.to_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/orders_final29.csv', index=False)

529769
24446
InvoiceNo      0
InvoiceDate    0
CustomerID     1
TotalAmount    0
PaymentMode    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24446 entries, 0 to 24445
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    24446 non-null  object
 1   InvoiceDate  24446 non-null  object
 2   CustomerID   24445 non-null  float64
 3   TotalAmount  24446 non-null  float64
 4   PaymentMode  24446 non-null  object
dtypes: float64(2), object(3)
memory usage: 1.1+ MB
None
   InvoiceNo   InvoiceDate  CustomerID  TotalAmount      PaymentMode
0     536365  12/1/10 8:26     17850.0       139.12       Debit Card
1     536366  12/1/10 8:28     17850.0        22.20    Bank Transfer
2     536367  12/1/10 8:34     13047.0       278.73           PayPal
3     536368  12/1/10 8:34     13047.0        70.05       Debit Card
4     536369  12/1/10 8:35     13047.0        17.85       Debit Card
5     536370  12/1/10 8:45     12583.0       855.86           PayPal
6     536371  12/1/10 9:00     13748.0       204.00       Debit Card
7     536372  12/1/10 9:01     17850.0        22.20  Mobile Payments
8     536373  12/1/10 9:02     17850.0       259.86  Mobile Payments
9     536374  12/1/10 9:09     15100.0       350.40       Debit Card
10    536375  12/1/10 9:32     17850.0       259.86    Bank Transfer
11    536376  12/1/10 9:32     15291.0       328.80       Debit Card
12    536377  12/1/10 9:34     17850.0        22.20       Debit Card
13    536378  12/1/10 9:37     14688.0       444.98  Mobile Payments
14    536380  12/1/10 9:41     17809.0        34.80      Credit Card
15    536381  12/1/10 9:41     15311.0       446.23      Credit Card
16   C536379  12/1/10 9:41     14527.0       -27.50      Credit Card
17    536382  12/1/10 9:45     16098.0       430.60             Cash
18   C536383  12/1/10 9:49     15311.0        -4.65    Bank Transfer
19    536384  12/1/10 9:53     18074.0       489.60            Check
24446

/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/2736496689.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Orders['TotalAmount'] = Orders['Quantity'] * Orders['UnitPrice']
/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/2736496689.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Orders['InvoiceNo'] = Orders['InvoiceNo'].str.upper()

In [90]:
#4. Customers Table

Customers = final_data[['CustomerID', 'Country']]
Customers['CustomerID'] = Customers['CustomerID'].str.upper()
Customers = Customers.drop_duplicates(subset='CustomerID')


print(Customers['CustomerID'].nunique())

# Add phone number
# List of some common US area codes
area_codes = [202, 212, 213, 305, 310, 312, 415, 425, 503, 510, 512, 617, 619, 626, 650, 702, 718, 805, 818, 914]

# Function to generate a random US phone number with a valid area code
def generate_us_phone_number(area_codes):
    area_code = random.choice(area_codes)
    exchange_code = random.randint(100, 999)
    subscriber_number = random.randint(1000, 9999)
    return f"({area_code}) {exchange_code}-{subscriber_number}"

# Generate 5943 distinct phone numbers
phone_numbers_set = set()
while len(phone_numbers_set) < 4373:
    phone_number = generate_us_phone_number(area_codes)
    phone_numbers_set.add(phone_number)

# Convert the set to a list
phone_numbers_list = list(phone_numbers_set)

if len(Customers) >= 4373:
    Customers['PhoneNumber'] = phone_numbers_list
else:
    print("Customers DataFrame has fewer rows than the number of phone numbers to be added.")

#%%
#print(Customers.head(15))

from faker import Faker

# Initialize a Faker generator
fake = Faker()

# Generate random first and last names
if len(Customers) >= 4373:
    Customers['FirstName'] = [fake.first_name() for _ in range(len(Customers))]
    Customers['LastName'] = [fake.last_name() for _ in range(len(Customers))]
else:
    print("Customers DataFrame has fewer rows than the required number for name generation.")

#print(Customers.head(15))

new_column_order = ['CustomerID', 'FirstName', 'LastName', 'PhoneNumber', 'Country']

# Reorder the columns in Customers DataFrame
Customers = Customers[new_column_order]
#print(Customers.head(15))

from datetime import datetime, timedelta

def random_date(start, end):
    """Generate a random date between `start` and `end`."""
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = random.randrange(int_delta)
    return start + timedelta(seconds=random_second)


# Define the date ranges for Date_of_Birth
dob_start = datetime(1950, 1, 1).date()
dob_end = datetime(2000, 1, 1).date()

# Populate Date_of_Birth
Customers['Date_of_Birth'] = [random_date(dob_start, dob_end) for _ in range(len(Customers))]

# Populate Gender randomly
Customers['Gender'] = [random.choice(["Male", "Female"]) for _ in range(len(Customers))]

# Define the date range for CustomerSince, ensuring it's at least 8 years after Date_of_Birth
Customers['CustomerSince'] = [
    random_date(max(dob, datetime(1990, 1, 1).date()) + timedelta(days=8*365), datetime(2011, 12, 9).date()) 
    for dob in Customers['Date_of_Birth']
]


#print(Customers.head(20))

new_column_order = ['CustomerID', 'FirstName', 'LastName', 'Gender', 'PhoneNumber', 'Date_of_Birth', 'CustomerSince', 'Country']
Customers = Customers[new_column_order]
Customers = Customers.dropna(subset='CustomerID')
print(Customers[Customers['CustomerID'].isnull()])
print(Customers.dtypes)
Customers['CustomerID'] = Customers['CustomerID'].astype(float)
Customers['CustomerID'] = Customers['CustomerID'].astype(int)
print(Customers.dtypes)
Customers['CustomerID'] = Customers['CustomerID'].astype('string')
#Customers['CustomerID']  = Customers['CustomerID'].astype('string')
print(Customers.head(20))
print(len(Customers))

#%%
Customers.to_csv('/Users/bhoomikan/Desktop/Datawarehousing/final_files/customers_final29.csv', index = False)

/var/folders/r6/q3x1v4bd3wx6jsgq988svh6m0000gn/T/ipykernel_17219/2167204148.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Customers['CustomerID'] = Customers['CustomerID'].str.upper()

4372
Empty DataFrame
Columns: [CustomerID, FirstName, LastName, Gender, PhoneNumber, Date_of_Birth, CustomerSince, Country]
Index: []
CustomerID       string
FirstName        object
LastName         object
Gender           object
PhoneNumber      object
Date_of_Birth    object
CustomerSince    object
Country          object
dtype: object
CustomerID        int64
FirstName        object
LastName         object
Gender           object
PhoneNumber      object
Date_of_Birth    object
CustomerSince    object
Country          object
dtype: object
    CustomerID  FirstName   LastName  Gender     PhoneNumber Date_of_Birth  \
0        17850      Julie     Jordan  Female  (718) 416-6242    1969-12-20
9        13047       John  Rodriguez    Male  (914) 962-6680    1999-01-22
26       12583      Karen       Wood    Male  (702) 603-9810    1960-08-27
46       13748     Brenda     Carter    Male  (718) 634-8770    1969-12-30
65       15100       Sean      James  Female  (312) 362-2677    1999-12-22
82       15291      James   Franklin  Female  (415) 913-3311    1964-10-27
86       14688    Michael   Harrison    Male  (617) 276-9889    1990-02-25
105      17809       Adam      Combs  Female  (512) 754-7628    1950-05-16
106      15311       Chad     Haynes  Female  (619) 502-1078    1987-02-09
140      14527   Veronica  Hernandez    Male  (818) 233-5181    1993-11-12
141      16098     Sharon       Holt  Female  (202) 894-9676    1991-11-13
154      18074      Angel     Haynes  Female  (914) 405-5440    1957-12-28
167      17420    William       Bass    Male  (510) 450-8372    1968-04-16
174      16029    Stephen   Woodward    Male  (617) 844-3284    1998-05-21
182      16250      Jason     Holder  Female  (619) 252-7682    1992-07-14
196      12431      Linda      Scott  Female  (415) 786-3589    1951-07-26
210      17511      Sarah       Hall  Female  (805) 518-9526    1999-07-18
234      17548    Rebekah   Martinez    Male  (818) 102-1958    1995-12-12
241      13705  Dominique       York  Female  (626) 986-4735    1993-08-07
251      13747       Cody     Morgan    Male  (213) 526-8125    1978-01-16

    CustomerSince         Country
0      1999-10-24  United Kingdom
9      2007-05-23  United Kingdom
26     2009-06-08          France
46     2002-02-27  United Kingdom
65     2010-04-19  United Kingdom
82     2000-08-10  United Kingdom
86     1998-03-07  United Kingdom
105    2006-11-27  United Kingdom
106    2000-05-23  United Kingdom
140    2003-02-10  United Kingdom
141    2008-10-18  United Kingdom
154    2006-02-08  United Kingdom
167    2000-11-19  United Kingdom
174    2008-07-06  United Kingdom
182    2011-11-01  United Kingdom
196    2007-04-01       Australia
210    2009-06-08  United Kingdom
234    2008-01-23  United Kingdom
241    2001-10-20  United Kingdom
251    1998-06-02  United Kingdom
4372